# Generated by Django 6.0.5 on 2026-05-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-id'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
