# Generated by Django 6.0.5 on 2026-05-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_task_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]


